name: ci
on: [push, pull_request]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run docker-compose
        run: docker-compose -f tests/docker-compose.yml up -d
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - uses: dschep/install-poetry-action@v1.3
      - name: CI
        run: make ci
